I broke the termux build. First attempt to fix it.
pkg/mod/github.com/gcla/termshark@v1.0.1-0.20191014013336-ea9649016c9b/system/fd.go:61:9: undefined: Dup2