Fix a build break on Go < 1.14
This was the error:

ui/ui.go:517:2: duplicate method Length
ui/ui.go:546:39: rowFocusTableWidget.Length is ambiguous
ui/ui.go:546:39: cannot use res (type *rowFocusTableWidget) as type list.IBoundedWalker in argument to list.NewBounded:
	*rowFocusTableWidget does not implement list.IBoundedWalker (missing Length method)
ui/ui.go:640:39: psmlTableRowWidget.Length is ambiguous
ui/ui.go:640:39: cannot use res (type *psmlTableRowWidget) as type list.IBoundedWalker in argument to list.NewBounded:
	*psmlTableRowWidget does not implement
	list.IBoundedWalker (missing Length method)

Go 1.14 allows this ambiguity by taking the set union of interface
methods.